### PR TITLE
Update _config.yaml

### PR DESCRIPTION
**Pull request by smutek**
Remove relative_permalinks: true and adds jekyll-paginate & jekyll-gist gems from _config.yml allowing for an error free jekyll serve

### CODE REVIEW

**Comment by kigster** [comment]
Please merge this PR – without it Poole does not work on Jekyll 3.*

**Comment by kotse** [comment]
This should be merged - new users are not supposed to lose time over this, when the configuration clearly says 
>just download Poole and start up Jekyll

Well it obviously doesn't...

That said, small documentation change is also needed with this commit - because those new required gems will not install themselves ;)

**Comment by nicolasmccurdy** [comment]
I agree that Jekyll 3 should be supported and that there should be more documentation about Jekyll 3 either way. However, wouldn't this change functionality on Jekyll 2, causing permalinks to be different? It's important to note that GitHub Pages is still using Jekyll 2 for now, so we don't want to break anything that uses it.

Also, there should be a Gemfile with these additional gem dependencies to make setup easier.

**Comment by kotse** [comment]
Valid point :)

So its better to put all Jekyll3 related in a separate branch ```jekyll_v3```, with ```Gemfile```, proper ```README```...

And just update README on master so people know where to look

**Comment by nicolasmccurdy** [comment]
@kotse It would be great if Jekyll 3 compatability could be implemented without affecting Jekyll 2, but if that isn't possible I would prefer a separate branch.

**Pull request merged**
